version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      dev-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production
